branches:
  only:
  - master

language: python
os: linux
dist: xenial

jobs:
  include:
  - name: pytest
    python:
      - 3.7
    install:
      - pip install -U pip
      - pip install -U pytest
      - pip install -U PyYAML
      - pip install -U Cerberus
    script:
      - pytest -vvs